// This file was generated by Mendix Business Modeler 5.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package webservice_ntlm.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the Microflows for the WebService_NTLM module

	public static boolean call_NTLMWebService(IContext context, system.proxies.FileDocument _request, system.proxies.FileDocument _response, String _soapAction, String _soapUrl)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("Request", _request == null ? null : _request.getMendixObject());
			params.put("Response", _response == null ? null : _response.getMendixObject());
			params.put("SoapAction", _soapAction);
			params.put("SoapUrl", _soapUrl);
			return (Boolean)Core.execute(context, "WebService_NTLM.Call_NTLMWebService", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static webservice_ntlm.proxies.NTLM_Config get_Config(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "WebService_NTLM.Get_Config", params);
			return result == null ? null : webservice_ntlm.proxies.NTLM_Config.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void show_Config(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			Core.execute(context, "WebService_NTLM.Show_Config", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}