// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package webservice_ntlm.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class NTLM_Config
{
	private final IMendixObject nTLM_ConfigMendixObject;

	private final IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "WebService_NTLM.NTLM_Config";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Username("Username"),
		Password("Password"),
		Domain("Domain"),
		UseWorkstation("UseWorkstation");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public NTLM_Config(IContext context)
	{
		this(context, Core.instantiate(context, "WebService_NTLM.NTLM_Config"));
	}

	protected NTLM_Config(IContext context, IMendixObject nTLM_ConfigMendixObject)
	{
		if (nTLM_ConfigMendixObject == null)
			throw new IllegalArgumentException("The given object cannot be null.");
		if (!Core.isSubClassOf("WebService_NTLM.NTLM_Config", nTLM_ConfigMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a WebService_NTLM.NTLM_Config");

		this.nTLM_ConfigMendixObject = nTLM_ConfigMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'new NTLM_Config(Context)' instead. Note that the constructor will not insert the new object in the database.
	 */
	@Deprecated
	public static webservice_ntlm.proxies.NTLM_Config create(IContext context) throws CoreException
	{
		IMendixObject mendixObject = Core.create(context, "WebService_NTLM.NTLM_Config");
		return new webservice_ntlm.proxies.NTLM_Config(context, mendixObject);
	}

	/**
	 * @deprecated Use 'NTLM_Config.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static webservice_ntlm.proxies.NTLM_Config initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return webservice_ntlm.proxies.NTLM_Config.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static webservice_ntlm.proxies.NTLM_Config initialize(IContext context, IMendixObject mendixObject)
	{
		return new webservice_ntlm.proxies.NTLM_Config(context, mendixObject);
	}

	public static webservice_ntlm.proxies.NTLM_Config load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return webservice_ntlm.proxies.NTLM_Config.initialize(context, mendixObject);
	}

	public static java.util.List<webservice_ntlm.proxies.NTLM_Config> load(IContext context, String xpathConstraint) throws CoreException
	{
		java.util.List<webservice_ntlm.proxies.NTLM_Config> result = new java.util.ArrayList<webservice_ntlm.proxies.NTLM_Config>();
		for (IMendixObject obj : Core.retrieveXPathQuery(context, "//WebService_NTLM.NTLM_Config" + xpathConstraint))
			result.add(webservice_ntlm.proxies.NTLM_Config.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(IContext context) throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(IContext context)
	{
		Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Username
	 */
	public final String getUsername()
	{
		return getUsername(getContext());
	}

	/**
	 * @param context
	 * @return value of Username
	 */
	public final String getUsername(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Username.toString());
	}

	/**
	 * Set value of Username
	 * @param username
	 */
	public final void setUsername(String username)
	{
		setUsername(getContext(), username);
	}

	/**
	 * Set value of Username
	 * @param context
	 * @param username
	 */
	public final void setUsername(IContext context, String username)
	{
		getMendixObject().setValue(context, MemberNames.Username.toString(), username);
	}

	/**
	 * @return value of Password
	 */
	public final String getPassword()
	{
		return getPassword(getContext());
	}

	/**
	 * @param context
	 * @return value of Password
	 */
	public final String getPassword(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Password.toString());
	}

	/**
	 * Set value of Password
	 * @param password
	 */
	public final void setPassword(String password)
	{
		setPassword(getContext(), password);
	}

	/**
	 * Set value of Password
	 * @param context
	 * @param password
	 */
	public final void setPassword(IContext context, String password)
	{
		getMendixObject().setValue(context, MemberNames.Password.toString(), password);
	}

	/**
	 * @return value of Domain
	 */
	public final String getDomain()
	{
		return getDomain(getContext());
	}

	/**
	 * @param context
	 * @return value of Domain
	 */
	public final String getDomain(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Domain.toString());
	}

	/**
	 * Set value of Domain
	 * @param domain
	 */
	public final void setDomain(String domain)
	{
		setDomain(getContext(), domain);
	}

	/**
	 * Set value of Domain
	 * @param context
	 * @param domain
	 */
	public final void setDomain(IContext context, String domain)
	{
		getMendixObject().setValue(context, MemberNames.Domain.toString(), domain);
	}

	/**
	 * @return value of UseWorkstation
	 */
	public final Boolean getUseWorkstation()
	{
		return getUseWorkstation(getContext());
	}

	/**
	 * @param context
	 * @return value of UseWorkstation
	 */
	public final Boolean getUseWorkstation(IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.UseWorkstation.toString());
	}

	/**
	 * Set value of UseWorkstation
	 * @param useworkstation
	 */
	public final void setUseWorkstation(Boolean useworkstation)
	{
		setUseWorkstation(getContext(), useworkstation);
	}

	/**
	 * Set value of UseWorkstation
	 * @param context
	 * @param useworkstation
	 */
	public final void setUseWorkstation(IContext context, Boolean useworkstation)
	{
		getMendixObject().setValue(context, MemberNames.UseWorkstation.toString(), useworkstation);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final IMendixObject getMendixObject()
	{
		return nTLM_ConfigMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final webservice_ntlm.proxies.NTLM_Config that = (webservice_ntlm.proxies.NTLM_Config) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "WebService_NTLM.NTLM_Config";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
